### ISSUE TITLE
how to use localforage-find in angular4 typescript

### ISSUE THREAD

**Issue by tamih** [psalaets/localforage-find#1]
Hi
I am using angular4+typescript+localforage .
In oreder to use localforage I import it like this: 
`import * as localForage from "localforage";`
how do I import localforage-find so I will be able to use it ? 
I tried 
`require('localforage-find')(localForage);`
but it didn't succeeded ...

**Comment by psalaets** [comment]
Try this

```js
import localforage from 'localforage';
import addFind from 'localforage-find';

addFind(localforage);
```

**Comment by tamih** [comment]
I added 
`import * as localForage from "localforage";
import   addFind from 'localforage-find';
addFind(localForage);`
but I didn't found how to call the find() function inside my class .
i.e. my code uses :
`this.store1.getItem(....).then(....)`
that I want to replace with find method.
can you please show me a small sample how to use it ?

**Comment by psalaets** [comment]
Take a look at this example: https://github.com/psalaets/localforage-find#with-promises

**Comment by tamih** [comment]
I tried that , but it didn't work.
localforage.find was not found 
find function was not added to localforage

**Comment by psalaets** [comment]
Ohh it looks like you're creating your own instance of localforage, not using the default instance.

The `find()` function was only being added to the default instance. I published an update so `find()` is available to all instances.

`localforage-find` verison `2.0.1` has that fix

**Comment by psalaets** [comment]
Haven't heard anything in over 30 days so I'm assuming you figured it out or gave up
